language: node_js

node_js:
  - '10'

branches:
  only:
    - master

install: npm install

script:
  - npm run test

deploy:
  provider: heroku
  api_key:
    secure: qj6Ut+wL8eBd0C0eaiacaVMoPZvLIscUqDAq1Cf7p+zecXRidFUWfEljPNCfFCGDwWHcaGvLPlDzc4SqFZKS/Jp4MLzst3HrvdJAmW0QkE+4bwvIPyoBQgySz9Nus93LMtB51PMisMWkOOI24PmlO5OWng2eg3RCExaNRek9WGb2i+EAddFOFXzqzFebH6tCn5J5cNcYXeRzw1XtMDNw2yVwuaI0Hz42XCLpFJQo3X3o6klh3JquZF/mN9mH9fqFfob9CBJ5uaXgs+awHXn/Zagysudg0rksHFZVxtnnapB/3mzwcH6647P5LKI/5kwtHR6NSFSRzHEBplpR5Ctc+LXewoJ9I6I7rlRNJgfR5C3K6HBqZdSEJRBDWdEHQamvK/yXheQNMNgmU1J49QABZo7hbHAq9InVHANvunzBpEPLWrScjr9rCi0GOVdpSKn6J0snVGfK27dPRsrF4RwViYeSYoDBeW0Iaim4AEjzIoJ0OMWQEzg4h5HAK2ciLp8WZqfnmFJpTOiyRiGsxIw86X1Q/JjMHX8XcAS/4sjy8YV5IIfZqRqIO7RpbbmAeXXALjeQdZkOkeMWACXjvBbkpeGZXXBgrhztTG5ka9+pA1p4zaGY0KkuzNxtUgdDB8QoJEBQ3E1OptH+ifzydZILTXNfBkncIJNsykj3y/jxaJE=
