language: node_js
node_js:
  - '10'
branches:
  only:
    - master
install: npm install
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: IksydwQPiFRKgqWSHGWr46NlnwYIy202QK+MSOpge2tW89w4fSgPqygHtIC1oPm7D8L7NypLGz6tcFPPOfM+BxvIOATp8lvRUU390SoKIVZ8+1+6NsjtVmtD7Q+zzVlTqvd+nm3E5VocSPsN4AHXBeDMl0yqdvTw0mr43FIl3zlb6OEhkqjyyxFIYHmQLiw9K+gkmedn3MQj5BLy/6TonmS9bZob/ECULYBUN2d0hQD473iX+DuRdc4TdxDF0jqY8RDi4cvLgzzc25k6/23YCfhrTZO16uXJtpEJoOuhGOR4HTB3qk31TokDapcWcFXAahHAKkf2iBUZSlp4CYlLfigPEGwTUWb5qpjOfp/MKO92MAkPvBAdGId8dFlk/Zho8o27OSiWd9hBNfZYtCVvtYubdyAKs2Dy1+1TrdpXMNYllNuCid4WZ23k/S0+qcgUgI7CKTMhFztCzfn/t4wgnDbL4QyVHMN96SUI5plmlI3gERF7hdIV1SdMdsHOwIcuV4CvbitP0ZVYIu79P/n6wqbKGUO3ofQPArZizoWK9VVuw3Ebhl70sNGZhEhT95Ad5LRQFrZImUdiDlTe5hprUakpu691q0uo0Z+C9jYykBahgCTopIuJRizQRhAFO4mrzYFDQhhQtfcA7T3jtQhcajAj4YWWJGn0qIxct2REFd8=
  app: quotes-server-stage
  on:
    repo: webbeast2019/hello-cicd-backend
